services:
  web:
    build: ./backend
    container_name: flask_app
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app 

  db:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    container_name: react_app
    ports:
      - "3000:80"
    depends_on:
      - web

volumes:
  postgres_data:
