services:
  web:
    build: ./backend
    container_name: flask_app
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - ./.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: react_app
    ports:
      - "3000:80"
    depends_on:
      - web

volumes:
  postgres_data:
