"""Meals tables

Revision ID: 9946b7edc369
Revises: 5ea877d9ec43
Create Date: 2024-10-04 20:54:23.706133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9946b7edc369'
down_revision = '5ea877d9ec43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE meals_on_event_id_seq START WITH 1 INCREMENT BY 1")
    op.create_table('meals_on_event',
        sa.Column('id', sa.Integer(), sa.Sequence('meals_on_event_id_seq'), nullable=False),
        sa.Column('name', sa.Unicode(length=100), nullable=False),
        sa.Column('meal_type', sa.Unicode(length=50), nullable=False),
        sa.Column('is_vegetarian', sa.Boolean(), nullable=False),
        sa.Column('event_id', sa.Integer(), sa.ForeignKey('events.id'), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column('creation_date', sa.DateTime(), nullable=False),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.Column('update_date', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.execute("CREATE SEQUENCE participant_meals_on_event_id_seq START WITH 1 INCREMENT BY 1")
    op.create_table('participant_meals_on_event',
        sa.Column('id', sa.Integer(), sa.Sequence('participant_meals_on_event_id_seq'), nullable=False),
        sa.Column('meal_id', sa.Integer(), sa.ForeignKey('meals_on_event.id'), nullable=False),
        sa.Column('participant_id', sa.Integer(), sa.ForeignKey('participants.id'), nullable=False),
        sa.Column('is_special_request', sa.Boolean(), nullable=True, server_default=sa.sql.expression.false()),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column('creation_date', sa.DateTime(), nullable=False),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.Column('update_date', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant_meals_on_event')
    op.execute("DROP SEQUENCE participant_meals_on_event_id_seq")

    op.drop_table('meals_on_event')
    op.execute("DROP SEQUENCE meals_on_event_id_seq")
    # ### end Alembic commands ###
