"""event id on participant meal

Revision ID: e81e82b4ec68
Revises: 9946b7edc369
Create Date: 2024-10-05 10:47:41.410006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81e82b4ec68'
down_revision = '9946b7edc369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant_meals_on_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('day', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant_meals_on_event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('day')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
